version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "80:80"  # Expose port 80 for WordPress
    environment:
      WORDPRESS_DB_HOST: wordpress-dbb.ce34ummwsias.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin1234
      WORDPRESS_DB_NAME: wordpress-dbb
    volumes:
      - wordpress_data:/var/www/html

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"  # Expose port 8080 for Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html

volumes:
  wordpress_data:
